### ISSUE TITLE
Incompatible argument types

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-interfaces#101]
The pubsub [_publish](https://github.com/libp2p/js-libp2p-interfaces/blob/master/src/pubsub/index.js#L696) method takes an arg of `InMessage|RPCMessage`.

`InMessage` has an optional [from](https://github.com/libp2p/js-libp2p-interfaces/blob/master/src/pubsub/index.js#L36) field of type `string`, `RPCMessage` has an optional [from](https://github.com/libp2p/js-libp2p-interfaces/blob/master/src/pubsub/message/rpc.js#L351) field of `Uint8Array|undefined`.

These are not compatible.  Which one is correct?

**Comment by achingbrain** [comment]
It looks to me like it's only every going to be a `Uint8Array` since messages passed to `_publish` first go through [normalizeOutRpcMessage](https://github.com/libp2p/js-libp2p-interfaces/blob/3042dc2a3b27ebe4a06c4c856f582f997d0bbe48/src/pubsub/utils.js#L126-L137) which turns string `from` fields into `Uint8Array`s if they are present but I'm not sure if this is the intention or not.

**Comment by achingbrain** [comment]
Actually sometimes it can be a string. I think this only ever worked in the past because the CID constructor took so many input types.

**Comment by vasco-santos** [comment]
It is computed in https://github.com/libp2p/js-libp2p-interfaces/blob/master/src/pubsub/utils.js#L100 and I think the `from` optional field is for the signature validation. Perhaps @wemeetagain can give more insights, I don't recall exactly the reasoning

**Comment by wemeetagain** [comment]
Sorry late reply here, but the reason for the difference is related to https://github.com/libp2p/js-libp2p/issues/680

It's more convenient for the `from` field to be a string peer id.
But the protobuf expects the Uint8Array representation of the `from` field.

The `normalize*RpcMessage` functions were there to translate between these two worlds, user-facing InMessage object vs wire RPCMessage object.

That `_publish` interface was too flexible, not great. It looks like that `_publish` interface wasn't (isn't) respected in js-libp2p-gossipsub: [`_publish(msg: InMessage): Promise<void>`.](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/ts/index.ts#L1041)
