### ISSUE TITLE
Module not found: Can't resolve 'libp2p-connection'

### ISSUE THREAD

**Issue by nrz123** [libp2p/js-libp2p-interfaces#115]
when i use libp2p-connection in react
npm i libp2p-connection
and
import { Connection } from 'libp2p-connection'
there is a error
Module not found: Can't resolve 'libp2p-connection' in 'D:\tk\src'

**Comment by mpetrunic** [comment]
@nrz123  Could you post some source code example?

**Comment by BigLep** [comment]
Closing for now without more info.  This issue was also opened in 202112 and js-libp2p has had various upgrades since then.
