### ISSUE TITLE
Questions about stream muxer behavior

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p-interfaces#224]
Questions:
- What's the intended behavior for an initiator and recipient for `abort` and `reset`? When should each be called?
- Does `closeWrite` close the stream for writing immediately? or does it wait for the stream to be drained first before closing the write side?
-Does `closeRead` close the stream for reading immediately? or does it wait for the stream to be drained first before closing the read side?
- What happens if `closeWrite` is called while the sink is not yet drained, ie still processing a source?

Answers (?):
- If an initiator wants to trigger a stream to be reset (ended for both reading and writing because of some error), they should call `abort`.
`abort` will stop the stream from further reading/writing, but first notify the recipient. The recipient will likely then call `reset`.
`reset` will stop the stream from further reading/writing, without notifying the recipient.
- `closeWrite` notifies the recipient to no longer expect any more data and immediately closes the write side of the stream.
- `closeRead` immediately closes the read side of the stream.
- If `closeWrite` is called while the sink is still processing a source, the processing will stop after the current iteration and the sync will return normally (not throw).

**Comment by achingbrain** [comment]
Closing as questions have been answered.
