### ISSUE TITLE
PeerId string identifier

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p-interfaces#256]
I think we could simplify and improve the performance of all downstream implementations of most interfaces by representing a peer id as a string.

See https://github.com/libp2p/js-libp2p/issues/680 for more rationale

The peer id spec describes [string representation](https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md#string-representation). We would declare the CID representation as canonical and use that everywhere.

interface may look like:
```ts
export type PeerIdCID = string
```

**Comment by mpetrunic** [comment]
Triage suggestion: toString is caching string representation. Tip: use PeerMap
