### ISSUE TITLE
Add support for metrics labels

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p-interfaces#257]
See https://github.com/siimon/prom-client#labels

Sometimes we want metrics with specific labels, eg:
![metrics-labels](https://user-images.githubusercontent.com/1348242/175133263-2c96c4c0-e4e8-44ed-9a96-948ae602ecf2.png)

In this example, the metric was set up and used like so:
```ts
const peerGauge = new Gauge({
  name: 'peer_count',
  help: 'peer count',
  labels: ['direction']
})

peerGauge.set({direction: 'inbound'}, 25)
peerGauge.set({direction: 'outbound'}, 25)
```

The metrics interface should support some way to do this.

**Comment by achingbrain** [comment]
Sounds good.  As long as we can keep prometheus-specific stuff out of the codebase, this would be really great to have.  I'd like to graph protocol counts together as well, for example.
