### ISSUE TITLE
[peer discovery] Add test suite and add it to all implementations

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p-interfaces#26]
Currently this repo has no test suite, it needs one. Once that's in place, all current implementations need to have the test suite added to them.

## Tests
- [ ] Ensure implementations conform to the api, https://github.com/libp2p/interface-peer-discovery#api
- [ ] Ensure discovery services do not emit their own `PeerInfo`. Ref: https://github.com/libp2p/js-libp2p/issues/356
  - _Note_: The api will need to change to pass in libp2p when the service is initialized so that it has knowledge of its own PeerInfo instance.

## Implementations
Add the test suite to:
- [x] [js-libp2p-mdns](https://github.com/libp2p/js-libp2p-mdns)
- [x] [js-libp2p-bootstrap](https://github.com/libp2p/js-libp2p-bootstrap)
- [ ] [js-libp2p-kad-dht randomWalk](https://github.com/libp2p/js-libp2p-kad-dht)
- [x] [js-libp2p-webrtc-star](https://github.com/libp2p/js-libp2p-webrtc-star)
- [ ] [js-libp2p-websocket-star](https://github.com/libp2p/js-libp2p-websocket-star)

**Comment by vasco-santos** [comment]
We already added these to each discovery implementation, except for the DHT. The DHT already has an issue to track it support once we refactor it
