### ISSUE TITLE
Question: why `secureOutbound` requires remotePeer?

### ISSUE THREAD

**Issue by melekes** [libp2p/js-libp2p-interfaces#286]
https://github.com/libp2p/js-libp2p-interfaces/tree/master/packages/interface-connection-encrypter#secure-outbound

The description says "If provided", but the interface enforces this. Why? Afaik, there's nothing from Noise protocol perspective, which requires the presence of remote peer ID.

**Comment by achingbrain** [comment]
This was a mistake - it was fixed in https://github.com/libp2p/js-libp2p-interfaces/pull/294
