### ISSUE TITLE
[transport] listener.close() *should* close existing connections and there should be .accept()/.reject() functions instead

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-libp2p-interfaces#30]
With the new proposal in place that transports don't close existing connections when stop is called and only stop to accept any new there arises a new bug: Connections will be left unclosed once the libp2p instance shuts down and will keep the process from exiting properly.

Instead there should be two new functions, .accept() and .reject(), that control whether or not a transport should accept new connections and .stop() should close all connections as usual.

**Comment by achingbrain** [comment]
Closing as this is very stale
