### ISSUE TITLE
events dispatchEvent typing

### ISSUE THREAD

**Issue by tabcat** [libp2p/js-libp2p-interfaces#317]
Is there any way to type check the Event.type and .detail for dispatchEvent similar to the add/removeEventListener methods?

https://github.com/libp2p/js-libp2p-interfaces/blob/913ddb522243c110318af7314015a156b8c889c1/packages/interfaces/src/events.ts#L63-L76

**Comment by mpetrunic** [comment]
Unfortunately, the Event type is of type string and there is no way to type-check it. I'm proposing new method with type safety here: https://github.com/libp2p/js-libp2p-interfaces/pull/319
