### ISSUE TITLE
Registrar and ConnectionManager missing from interface-libp2p

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p-interfaces#338]
Noticed this error upgrading to latest libp2p + gossipsub:
```
@lodestar/beacon-node: src/network/gossip/gossipsub.ts:98:11 - error TS2345: Argument of type 'Libp2p' is not assignable to parameter of type 'GossipSubComponents'.
@lodestar/beacon-node:   Type 'Libp2p' is missing the following properties from type 'GossipSubComponents': registrar, connectionManager
```

**Comment by p-shahi** [comment]
@maschad will investigate

**Comment by wemeetagain** [comment]
Current answer is https://github.com/libp2p/js-libp2p-interfaces/pull/339#pullrequestreview-1272936814

I still disagree with this.
We've gone through the trouble of making all these nice component interfaces, but the only consumer of the interfaces that's supported is Libp2p itself?

I understand the desire to guide users to a high level interface. Use docs, examples, educational materials, etc. to guide users.

I don't understand actively removing components from the interface. If downstream consumers respect the interface, it really hurts consumers who want to build new modules that act similarly to 'internal modules'. Even using 'internal modules' in non-standard ways becomes impossible.
So then many valid usecases will just resort to type hacking or even worse straight-up @ts-ignoring. All because we have strong opinions that the high level interface MUST be used.

**Comment by achingbrain** [comment]
This issue will be addressed by https://github.com/libp2p/js-libp2p/pull/1563 - the user will be able to define arbitrary services that have access to libp2p internal components to their hearts content.
