### ISSUE TITLE
Transport tests setup function should be more customisable

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p-interfaces#38]
[libp2p/js-interfaces/transport](https://github.com/libp2p/js-interfaces/tree/master/src/transport) tests should be refactored so that they can be used by modules with network setup requirements, such as `libp2p-stardust` and `circuit-relay`.

Both `stardust` and `circuit-relay` need the presence of a third party. We can have inspiration from the existing tests for `circuit-relay`

**Comment by achingbrain** [comment]
The tests all have async setup, any other changes needed can be made as and when.
