### ISSUE TITLE
Update peer and content routing return types in the readmes

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p-interfaces#48]
With the upcoming removal of PeerInfo we should fix the content / peer routing return types to better match other interfaces. When returning `{ id: <PeerId>, addrs: <Multiaddr[]> }`, we should instead return `{ id: <PeerId>, multiaddrs: <Multiaddr[]> }`.

Ref: https://github.com/libp2p/js-libp2p-delegated-peer-routing/pull/25#discussion_r412076997

cc @vasco-santos

**Comment by vasco-santos** [comment]
Closed in #49
