### ISSUE TITLE
Split the tests or interfaces out?

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-interfaces#58]
`ipfs-bitswap` has a runtime dependency on this module to pull in `MulticodecTopology` which means it ends up installing chai and sinon and whole bunch of other testing related modules.

This module depends on `libp2p-tcp` to run a test, and `libp2p-tcp` has a dev dependency on this module to pull in the tests.

This is a bit of a code smell, maybe either the tests or the interfaces should be in a separate module to break these weird dependency loops?

**Comment by vasco-santos** [comment]
Splitting makes sense to me! I would go with a new repo/module for the tests: `js-libp2p-interfaces-compliance`

What is your opinion @jacobheun ?

**Comment by jacobheun** [comment]
We should definitely avoid the test modules getting installed when base interfaces are being installed. I'd like to consider the usage more before just separating the two. Unless there is a strong need to get this fixed, let's revisit this in a couple months.

**Comment by BigLep** [comment]
@vasco-santos : what are the next steps on this issue?  If you're paused working on it, do you want to return to weekly candidates and denote what's next please?

**Comment by vasco-santos** [comment]
#97 has in the OP the remaining work. Basically handling the release of the multiple modules by updating the release scripts.
