### ISSUE TITLE
Questions around transport.filter

### ISSUE THREAD

**Issue by robertkiel** [libp2p/js-libp2p-interfaces#84]
The documentation says

> Filtering Addresses
>
>    const supportedAddrs = await transport.filter(multiaddrs)
>
> When using a transport its important to be able to filter out multiaddrs that the transport doesn't support. A transport instance provides a filter method to return only the valid addresses it supports.
>
> multiaddrs must be an array of type multiaddr. Filter returns an array of multiaddr.

While creating [HoprConnect](https://github.com/hoprnet/hopr-connect), we've seen that libp2p is calling transport.filter multiple times and for slightly different purposes.

- **at startup** to choose which Transport module we should choose for the given listening address
- **before every dial attempt** to find out which we transport we can use for the addresses that are known to us.

The reason why I'm asking so explicitly is that we have noticed that we need to keep the connection attempts as low as possible to not waste our resources for potentially unsuccessful connection attempts.

We therefore came to the idea to make `transport.filter` stateful to some extent. Meaning the transport module *knows* to which addresses we are listening, namely `libp2p.multiaddrs`, and is also able to *understand* its own network topology, so it should be able to decide where it makes sense to dial.

Examples:

We are bound to only IPv4 addresses but are now asked to connect to IPv6 as we've learned from the DHT -> dialling this address won't make sense.

We are available at `/ip4/127.0.0.1/tcp/12345` and get a request to dial `/ip4/127.0.0.1/tcp/12345` which obviously will lead to a self-dial and is most likely not what we were aiming for.

Same as public / external IPv4 addresses: Assume we knew that our NAT has assigned us to `/ip4/1.2.3.4/tcp/1234` which means that dial requests to `/ip4/1.2.3.4/tcp/1234` result in a self-dial.

**Comment by vasco-santos** [comment]
Hey @robertkiel 

> at startup to choose which Transport module we should choose for the given listening address
before every dial attempt to find out which we transport we can use for the addresses that are known to us.

Yes, that are the 2 use cases of the filter function in the transport.

> We therefore came to the idea to make transport.filter stateful to some extent.

In the typical libp2p transports, they are completely agnostic of libp2p, they just receive an upgrader per the [interface](https://github.com/libp2p/js-libp2p-interfaces/tree/master/src/transport#api). Then we started supporting transports with built in discovery like `webrtc-star`, which like `HoprConnect` are both transport and discovery. This means that we provided the libp2p instance to the transports and you can use it, like access its multiaddrs.

This optimisation seems nice for your context and I think you should do it. There is just one thing you should have in mind. `libp2p.multiaddrs` contains the multiaddrs that the node is advertising in the network. However, it does not mean the node is not listening on other addresses for instance. For a better observability, you can also check the [Address Manager](https://github.com/libp2p/js-libp2p/blob/master/src/address-manager/index.js).

**Comment by vasco-santos** [comment]
@robertkiel any further thing we should discuss in this context? Did you try it out?

**Comment by robertkiel** [comment]
I'm indeed trying it out at the moment. There were a few other things that we had to handle in the meantime. 

Will keep you updated and share my findings soon.

**Comment by robertkiel** [comment]
> Will keep you updated and share my findings soon.

Add a few other [check](https://github.com/hoprnet/hopr-connect/blob/main/src/filter.ts#L123-L181) in addition and it seems to work very well. The libp2p instance is failing very early on inappropriate address and not creating sockets and organisational overhead.

**Comment by lidel** [comment]
I'm closing this as this is not actionable enough (yet).
Feel free to continue discussion and open a more actionable issue/PRs when things get solidified enough?
